# galera_new_cluster
# Autogenerated from man page /usr/local/share/man/man1/galera_new_cluster.1
complete -c galera_new_cluster -l help --description '.'
complete -c galera_new_cluster -s h --description '.'

