# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
complete -c git-config -l color-moved --description 'in git-diff(1).  If simply set to true the default color mode will be used.'

