# git-show
# Autogenerated from man page /usr/local/share/man/man1/git-show.1
complete -c git-show -l unfold --description 'option was given.  E. g. , %(trailers:only:unfold) to do both.'
complete -c git-show -l color-moved --description '.'

