# git-branch
# Autogenerated from man page /usr/local/share/man/man1/git-branch.1
complete -c git-branch -s c -l copy --description 'Copy a branch and the corresponding reflog.'
complete -c git-branch -s C --description 'Shortcut for --copy --force.'

