# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
complete -c git-format-patch -l progress --description 'Show progress reports on stderr as patches are generated.'

