# git-diff-tree
# Autogenerated from man page /usr/local/share/man/man1/git-diff-tree.1
complete -c git-diff-tree -l color-moved --description '.'
complete -c git-diff-tree -l unfold --description 'option was given.  E. g. , %(trailers:only:unfold) to do both.'

