# git-merge
# Autogenerated from man page /usr/local/share/man/man1/git-merge.1
complete -c git-merge -l signoff --description 'Add Signed-off-by line by the committer at the end of the commit log message.'

