# git-rev-parse
# Autogenerated from man page /usr/local/share/man/man1/git-rev-parse.1
complete -c git-rev-parse -l is-shallow-repository --description 'When the repository is shallow print "true", otherwise "false".'

