# git-rev-list
# Autogenerated from man page /usr/local/share/man/man1/git-rev-list.1
complete -c git-rev-list -l single-worktree --description 'By default, all working trees will be examined by the following options when …'
complete -c git-rev-list -l unfold --description 'option was given.  E. g. , %(trailers:only:unfold) to do both.'

