# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
complete -c git-log -l single-worktree --description 'By default, all working trees will be examined by the following options when …'
complete -c git-log -l indexed-objects --description '.'
complete -c git-log -l unfold --description 'option was given.  E. g. , %(trailers:only:unfold) to do both.'
complete -c git-log -l color-moved --description '.'

