# git-for-each-ref
# Autogenerated from man page /usr/local/share/man/man1/git-for-each-ref.1
complete -c git-for-each-ref -l count --description 'By default the command shows all refs that match <pattern>.'
complete -c git-for-each-ref -l sort --description 'A field name to sort on.  Prefix - to sort in descending order of the value.'
complete -c git-for-each-ref -l color --description '.'

