# git-filter-branch
# Autogenerated from man page /usr/local/share/man/man1/git-filter-branch.1
complete -c git-filter-branch -l state-branch --description 'This option will cause the mapping from old to new objects to be loaded from …'

